"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
// Generated by CoffeeScript 2.7.0
//!/usr/bin/env coffee
var main;

var _default = main = () => {};

exports.default = _default;

if (process.argv[1] === decodeURI(new URL(import.meta.url).pathname)) {
  console.log(await main());
  process.exit();
}