// Generated by CoffeeScript 2.7.0
//!/usr/bin/env coffee
var nt2json, require;

import {
  createRequire
} from 'module';

import json5 from 'json5';

require = createRequire(import.meta.url);

({nt2json} = require('./lib.node'));

export default (txt) => {
  var err, o;
  try {
    o = JSON.parse(nt2json(txt));
  } catch (error) {
    err = error;
    o = txt;
  }
  return json5.stringify(o);
};
