"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _module = require("module");

var _json = _interopRequireDefault(require("json5"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// Generated by CoffeeScript 2.7.0
//!/usr/bin/env coffee
var nt2json, _require;

_require = (0, _module.createRequire)(import.meta.url);
({
  nt2json
} = _require('./lib.node'));

var _default = txt => {
  var err, o;

  try {
    o = JSON.parse(nt2json(txt));
  } catch (error) {
    err = error;
    o = txt;
  }

  return _json.default.stringify(o);
};

exports.default = _default;