// Generated by CoffeeScript 2.7.0
//!/usr/bin/env coffee
var main;

export default main = () => {};

if (process.argv[1] === decodeURI((new URL(import.meta.url)).pathname)) {
  console.log((await main()));
  process.exit();
}
