// Generated by CoffeeScript 2.7.0
//!/usr/bin/env coffee
var nt2json, require;

import {
  createRequire
} from 'module';

require = createRequire(import.meta.url);

({nt2json} = require('./lib.node'));

export default (txt) => {
  var err;
  try {
    return nt2json(txt);
  } catch (error) {
    err = error;
    return txt;
  }
};
