"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _module = require("module");

// Generated by CoffeeScript 2.7.0
//!/usr/bin/env coffee
var nt2json, _require;

_require = (0, _module.createRequire)(import.meta.url);
({
  nt2json
} = _require('./lib.node'));

var _default = txt => {
  var err;

  try {
    return nt2json(txt);
  } catch (error) {
    err = error;
    return txt;
  }
};

exports.default = _default;